#!/usr/bin/env node
/**
 * Compose dist/client.js — the browser bundle the harness serves at
 * /plugins/dsh-crew/client.js — from src/client/ plus xterm.js.
 *
 * The module loader's format is one `window.__ModuleLoader__.load` call whose
 * factory receives `require`, assigns `exports.apply` / `.inject`, and returns
 * `module.exports`. Everything the plugin owns must be inside that factory,
 * because the loader runs the script to REGISTER the factory and materializes it
 * later; a side effect at script scope would fire at the wrong time.
 *
 * Unlike a plugin that only draws a line of text, this one carries a terminal
 * emulator, so it needs a real bundler. esbuild inlines xterm.js and its
 * stylesheet and leaves `react` as a require() the loader satisfies with the
 * shell's own instance — two React copies in one document break hooks.
 *
 * The output is committed, so installing this package needs no build step.
 *
 * Usage: `node scripts/build-client.mjs` writes the bundle;
 *        `node scripts/build-client.mjs --check` fails when it is stale.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const target = join(root, 'dist/client.js')

// The module-loader id must be the package name, because that is the id the
// Node half puts in the boot graph when it scans enabled Loader entries. An id
// that differs registers a factory nobody resolves, and the plugin silently
// never materializes — the client half is simply absent, with no error.
const { name: MODULE_ID } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const result = await build({
  entryPoints: [join(root, 'src/client/index.js')],
  bundle: true,
  write: false,
  // IIFE, not CJS: esbuild's CJS output replaces `module.exports` with a
  // `__esModule`-tagged namespace, and the harness Loader treats a namespace
  // with that marker as an ES module and looks for a default export it will not
  // find. A named IIFE result assigned by hand keeps the plain-object export
  // shape the Loader expects from a function plugin.
  format: 'iife',
  globalName: 'dshCrewClient',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  // The shell owns React; xterm and this plugin's own code are inlined.
  external: ['react', 'react-dom'],
  // xterm ships its stylesheet as a file. The loader has no network step at
  // materialization, so the CSS travels as a string and the plugin injects it.
  loader: { '.css': 'text' },
  legalComments: 'none',
})

const [output] = result.outputFiles
const bundle = `// GENERATED by scripts/build-client.mjs — edit src/client/ instead.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(MODULE_ID)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
${output.text.trimEnd()}
    exports.apply = dshCrewClient.apply;
    exports.inject = dshCrewClient.inject;
    return module.exports;
  }
});
`

mkdirSync(join(root, 'dist'), { recursive: true })

if (process.argv.includes('--check')) {
  const current = (() => {
    try {
      return readFileSync(target, 'utf8')
    } catch {
      return ''
    }
  })()
  if (current !== bundle) {
    process.stderr.write('build-client: dist/client.js is stale — run `node scripts/build-client.mjs`\n')
    process.exit(1)
  }
  process.stdout.write('build-client: dist/client.js is in sync\n')
} else {
  writeFileSync(target, bundle)
  process.stdout.write(`build-client: wrote dist/client.js (${(bundle.length / 1024).toFixed(1)} KB)\n`)
}
